name: Update Weather Data

on:
  schedule:
    # Atualiza diariamente às 00:00 UTC
    - cron: "0 0 * * *"

  workflow_dispatch: # Permite disparar manualmente se necessário

jobs:
  update-weather:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch and update weather data
      run: python update_weather.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add weather_data.json
        git commit -m "Update weather data"
        git push
